### ISSUE TITLE
Problem in the flow field with DOM + imodak = 1 and isoot = 1 (Moss) + Gas Combustion = d3p

### ISSUE THREAD

**Issue by YohannEude** [code-saturne/code_saturne#69] opened 2020-11-05 15:27 UTC
Hello,
I'm currently work on a CASE which have the following main options:
DOM + IMODAK =1 + D3P + ISOOT = 1
With this setup, I can see the impact of soot on the boundaries temperature and the absorption in the volume field when I compare to the same calculation but without soot (ISOOT=-1). BUT if I compare, the temperature, pressure, ym_ fraction in the volume field, everything is exactly identical between ISOOT = -1 and 1. It is like there is something break between the fluid and the radiation and the boundaries.
Remarks: If I compare with a test with ISOOT = 0 (constant fraction of product), the behaviour of the volume field is impacted (the pressure temperature etc in the volume change compare to ISOOT = -1).

Thanks again for your help,

Regards,

Yohann

**Comment by YvanFournier** [comment] 2020-11-05 21:03
Hello,

Do you have a very small test case you could post to reproduce this ? Or otherwise at least the logs (run_solver.log, performance.log, and setup.log) for each of the the isoot variants (-1, 0, 1) ?

Regards,

**Comment by YohannEude** [comment] 2020-11-06 08:14
No problem, I'm currently prepare something to share.

**Comment by YohannEude** [comment] 2020-11-06 09:03
Here the cases with the three option for isoot with a studymanager xml.
Don't hesitate to push the calculation at 1000s for isoot = 1 and -1 to compare the volume field (T P etc).

[VARIANTE_PRISME_ISOOT.zip](https://github.com/code-saturne/code_saturne/files/5500210/VARIANTE_PRISME_ISOOT.zip)

**Comment by YohannEude** [comment] 2020-11-09 13:04
Hi, I think that the main problem comes from the default clip on the enthalpy in the GUI which is actually 0... I changed to -1e+12 and I see now the impact on the volume field now.
Regards
Yohann

**Comment by YvanFournier** [comment] 2020-11-10 01:27
Ok good.

Checking the code, I see only one difference between isoot 0 at isoot -1, in `cs_rad_transfer_absorption`, in the modak arguments:

With isoot 0, the soot volume fraction argument in `cs_rad_transfer_modak` is based on:
`xsoot * cpro_ym3[cell_id] * crom[cell_id] / rosoot`
While with isoot -1, it is zero.

I don't know enough about the matching model to know whether this term should be large or small.

It is still strange in this case that the enthalpy reference does not start at zero. Looking at the temperature/enthalpy conversion functions, I would expect enthalpy to always be >= 0, but is is possible that some boundary flux or source terms bring it locally under zero. The issue seems to appear near the `fire` BC.

I would suggest running without radiation to check id this seems due to radiative or other BC's. The 1d wall law might also be the cause of the issue. Replacing it with the closest type of radiative wall BC (fixed exterior temperature) would also be interesting.

**Comment by YvanFournier** [comment] 2020-12-29 11:25
Since the combustion model specialists confirm the Enthalpy value may be negative and clipping should not be done at 0 (applied in commit 6c1ad5cb), we can close this issue now.

**Closed by YvanFournier** 2020-12-29 11:25 UTC
