### ISSUE TITLE
Particles loss

### ISSUE THREAD

**Issue by nicolastonello** [code-saturne/code_saturne#25] opened 2018-11-22 12:41 UTC
Some Lagrangian particles traverse a boundary where they were expected to bounce.  I will send you the case.

**Comment by MartinFerrand** [comment] 2018-12-07 16:04
The problem was caused by the advanced user modification of the newly injected particle position (which can create a cell change). The tracking is modified so that particles are not lost any-more.
It is fixed in commit a85271c.

**Closed by MartinFerrand** 2018-12-07 16:04 UTC
