### ISSUE TITLE
AttributeError: 'QVariant' object has no attribute 'toString'

### ISSUE THREAD

**Issue by thierry-FreeBSD** [code-saturne/code_saturne#44] opened 2019-05-09 10:42 UTC
Trying v5.3.3, `code_saturne gui` produces the following error:

```
  File "/usr/local/bin/code_saturne", line 76, in <module>
    retcode = cs.execute()
  File "/usr/local/lib/python2.7/site-packages/code_saturne/cs_script.py", line 91, in execute
    return self.commands[command](options)
  File "/usr/local/lib/python2.7/site-packages/code_saturne/cs_script.py", line 150, in gui
    return cs_gui.main(options, self.package)
  File "/usr/local/lib/python2.7/site-packages/code_saturne/cs_gui.py", line 196, in main
    mv = MainView(cmd_package = pkg, cmd_case = case)
  File "/usr/local/lib/python2.7/site-packages/code_saturne/Base/MainView.py", line 1346, in __init__
    self.Browser = BrowserView()
  File "/usr/local/lib/python2.7/site-packages/code_saturne/Base/BrowserView.py", line 385, in __init__
    self.model = TreeModel(from_qvariant(to_qvariant(tree), to_text_string))
  File "/usr/local/lib/python2.7/site-packages/code_saturne/Base/QtPage.py", line 144, in from_qvariant
    return convfunc(qobj.toString())
AttributeError: 'QVariant' object has no attribute 'toString'
```
Am I missing something?
Note: this is on FreeBSD.

**Comment by YvanFournier** [comment] 2019-05-09 13:25
Hello,

Which versions of Pyton and Qt are you using ? It seems you are in the PYQT_AP1 path, which should match PyQt4, but is not expected with PyQt5 (whether Python 2 or 3). If this is the case, it means the detection/setting of the API variant works differently on FreeBsd than on the Linux machines we have tested it on.

Based on your actual tool versions, I can suggest different tests/variants to try to solve this issue.

**Comment by thierry-FreeBSD** [comment] 2019-05-09 14:13
On FreeBSD, everything depending on Qt4 has been removed, and the default Python version is 2.7 (but 3.6 is available when needed).
I'm using py27-qt5* versions 5.12.1.

**Comment by paspro** [comment] 2019-05-09 19:27
I have the exact same problem on Ubuntu with Python 2.7.16 and PyQt5 5.12.1

**Comment by YvanFournier** [comment] 2019-05-11 01:09
So this seems to be a Python2+Qt5 issue.

We have tested mostly with Python2+Qt4 and Python3+Qt5, though I did run some Python2+Qt5 some time ago.

I do not currently have access to such a combination (the machine I had VM's on died, its replacement is not yet set up).

Could you try replacing `bin/sc_gui.py` with the version from the `master` branch ? A change in this file (trying to force the Sip API to API2) which I had thought a bit risky for v6.0 might actually solve the issue. It it works, I'll simply cherry-pick that part of the matching commit in v6.0.

**Comment by thierry-FreeBSD** [comment] 2019-05-11 08:15
Sorry, I get the same message with the latest `bin/cs_gui.py`:

```
$ Traceback (most recent call last):
  File "/usr/local/bin/code_saturne", line 76, in <module>
    retcode = cs.execute()
  File "/usr/local/lib/python2.7/site-packages/code_saturne/cs_script.py", line 91, in execute
    return self.commands[command](options)
  File "/usr/local/lib/python2.7/site-packages/code_saturne/cs_script.py", line 150, in gui
    return cs_gui.main(options, self.package)
  File "/usr/local/lib/python2.7/site-packages/code_saturne/cs_gui.py", line 199, in main
    mv = MainView(cmd_package = pkg, cmd_case = case)
  File "/usr/local/lib/python2.7/site-packages/code_saturne/Base/MainView.py", line 1346, in __init__
    self.Browser = BrowserView()
  File "/usr/local/lib/python2.7/site-packages/code_saturne/Base/BrowserView.py", line 385, in __init__
    self.model = TreeModel(from_qvariant(to_qvariant(tree), to_text_string))
  File "/usr/local/lib/python2.7/site-packages/code_saturne/Base/QtPage.py", line 144, in from_qvariant
    return convfunc(qobj.toString())
AttributeError: 'QVariant' object has no attribute 'toString'

[1]  + exit 1     code_saturne gui

```

**Comment by YvanFournier** [comment] 2019-05-11 12:48
Ok, it seems we are stuck in the API1 mode, even though we tried to force API2 (which usually happens only when API1 is forced first during the same program execution...)

I'll need to check things as I had anticipated removing API1 support on the master branch (which will impact v6.1 next fall).

In the meantime, to confirm this, could you edit `gui/Base/QtPage.py`, and replace line 121:

```
    if QT_API == "PYQT4":
```
With:

```
    if sys.version_info[0] == 2:
```

Our test for Sip is based on the Qt API, maybe it should be based on the Python version...

**Comment by thierry-FreeBSD** [comment] 2019-05-11 16:08
With this patch, we get a different message:
```

$ Traceback (most recent call last):
  File "/usr/local/bin/code_saturne", line 76, in <module>
    retcode = cs.execute()
  File "/usr/local/lib/python2.7/site-packages/code_saturne/cs_script.py", line 91, in execute
    return self.commands[command](options)
  File "/usr/local/lib/python2.7/site-packages/code_saturne/cs_script.py", line 150, in gui
    return cs_gui.main(options, self.package)
  File "/usr/local/lib/python2.7/site-packages/code_saturne/cs_gui.py", line 195, in main
    from code_saturne.Base.MainView import MainView
  File "/usr/local/lib/python2.7/site-packages/code_saturne/Base/MainView.py", line 78, in <module>
    from code_saturne.Base.BrowserView import BrowserView
  File "/usr/local/lib/python2.7/site-packages/code_saturne/Base/BrowserView.py", line 50, in <module>
    from code_saturne.Base.QtPage import to_qvariant, from_qvariant, to_text_string
  File "/usr/local/lib/python2.7/site-packages/code_saturne/Base/QtPage.py", line 123, in <module>
    PYQT_API_1 = sip.getapi('QVariant') == 1
ValueError: unknown API 'QVariant'

[1]  + exit 1     code_saturne gui

```

**Comment by YvanFournier** [comment] 2019-05-11 17:13
This sort of issue is probably why we do not have more robust tests.. The code should not exit when we are running this test inside a "try... except..." construct, but does. So we need to work around a Sip bug...

A solution would be to run more tests at the configure stage, but I am still not sure how PyQt and Sip are behaving here...

A last test would be to ignore detection and assme API2 by replacing:
`PYQT_API_1 = sip.getapi('QVariant') == 1`
with:
`PYQT_API_1 = False`

(or remove the test altogether as it is already placed before)

**Comment by YvanFournier** [comment] 2019-05-11 17:22
Another simpler possible cause may be that the QT_API environment variable might be set incorrectly (if this is the case, we can solve that later).

What happens if you simply  `export QT_API=PYQT5` before running the GUI ?

**Comment by thierry-FreeBSD** [comment] 2019-05-12 10:57
> A last test would be to ignore detection and assme API2 by replacing:
> `PYQT_API_1 = sip.getapi('QVariant') == 1`
> with:
> `PYQT_API_1 = False`

I tried the hereunder patch, but since it is enclosed in  `if QT_API == "PYQT4"`, that does not change anything:

```
--- gui/Base/QtPage.py.orig	2019-05-07 12:03:47 UTC
+++ gui/Base/QtPage.py
@@ -120,7 +120,7 @@ if os.environ.get('QT_API', 'pyqt') == 'pyqt':
     import sip
     if QT_API == "PYQT4":
         try:
-            PYQT_API_1 = sip.getapi('QVariant') == 1
+            PYQT_API_1 = False
         except AttributeError:
             PYQT_API_1 = True
 
```

**Comment by thierry-FreeBSD** [comment] 2019-05-12 10:57
> What happens if you simply `export QT_API=PYQT5` before running the GUI ?

This one does the trick!

**Comment by thierry-FreeBSD** [comment] 2019-05-12 11:01
Hmm, sorry... The first screen is displayed, but when one tries to do something, it aborts quickly.
E.g.:

```
$ Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/code_saturne/Base/MainView.py", line 1181, in displayNewPage
    self.tr('OK'))
TypeError: information(QWidget, str, str, buttons: Union[QMessageBox.StandardButtons, QMessageBox.StandardButton] = QMessageBox.Ok, defaultButton: QMessageBox.StandardButton = QMessageBox.NoButton): argument 4 has unexpected type 'unicode'
QSocketNotifier: Invalid socket 11 and type 'Read', disabling...
QSocketNotifier: Invalid socket 13 and type 'Read', disabling...

```

**Comment by YvanFournier** [comment] 2019-05-13 00:34
Are all the Qt4 and PyQt4 libraries removed from the system ?
Just in case, adding `QT_SELECT=5` to the configure command could help if we have both versions installed.

But it really seems as if in your system there are incomplete remnants of Qt4, or I do not understand what is going on yet.

**Comment by thierry-FreeBSD** [comment] 2019-05-13 20:22
Everything related to Qt4 has been removed.
Anyway, I tried to pass `QT_SELECT=5`, but there is no effect...

**Comment by YvanFournier** [comment] 2019-05-14 12:29
OK, I guess I will need to generate a small "standalone" test case for this, unless I can reproduce it under a VM I have access to. I probably won't have access to a relevant machine before 2 weeks,  I'll try the standalone test before that.

Any additional feedback or idea in the meantime is of course welcome.

**Comment by thierry-FreeBSD** [comment] 2019-05-19 19:22
Good news: everything is fine with Python 3.6!

**Comment by YvanFournier** [comment] 2019-06-03 23:54
On my side, I re-tested on Arch Linux with both Python 2 and 3, and did not reproduce the issue, even when using python3's pyuic5 instead of python2-pyuic, which can be forced on the configure line, but might not be selected correctly based on priority when both are present (I suspected this could explain the issue).

I'm tempted to close the issue, as things are OK with Python 3, and Python 2 is on the way out, but I"ll wait a bit longer to test on Ubuntu if I have time or wait for additional feedback.

**Comment by YvanFournier** [comment] 2019-06-30 17:24
Also tested on Ubuntu 18.04, issue not reproduced.

**Closed by YvanFournier** 2019-06-30 17:24 UTC
